hello:hello.o
	./hello.o

hello.o:hello.c
	gcc hello.c -o hello.o 

# hello.c:
#	echo "#include <stdio.h>" > hello.c
#	echo "int main(void){printf("Welcome!");return 0;}" > hello.c
#	echo "int main(void){return 0;}" > hello.c